export interface Pod {
  name: string;
  vers: string;
  versionCount: number;
  olive_req?: string;
  deps: { name: string; req: string }[];
  by?: string;
  description?: string;
  dl?: string;
  yanked?: boolean;
}

export const INDEX_URL = 'https://ecnivslabs.github.io/pit-registry/index.json';

// The registry index is generated by a workflow in pit-registry and served
// from its GitHub Pages. Until that's deployed (or if it's ever unreachable
// at build time), fall back to the one pod actually published today so the
// site still builds and shows real data, not nothing.
const FALLBACK_PODS: Pod[] = [
  {
    name: 'term',
    vers: '0.1.5',
    versionCount: 6,
    olive_req: '0.42.4',
    deps: [],
    by: 'vinceswu',
    description:
      'Terminal support — raw mode, keyboard and mouse input, cursor control, flicker-free redraws, and clipboard access via OSC 52.',
    dl: 'https://github.com/vinceswu/term/releases/download/term-0.1.5/term.pit.zst',
  },
];

export async function fetchPods(): Promise<Pod[]> {
  try {
    const res = await fetch(INDEX_URL);
    if (res.ok) {
      const data = await res.json();
      if (Array.isArray(data.pods) && data.pods.length > 0) return data.pods;
    }
  } catch {
    // Registry index not reachable -- keep the fallback below.
  }
  return FALLBACK_PODS;
}

// Pods publish today by attaching a .pit.zst archive to a GitHub release
// (pit-registry's own CI verifies `dl` this way), so the repo a pod comes
// from can be read straight out of its download URL -- no separate `repo`
// field needed in the registry format.
const GITHUB_RELEASE_DL = /^https:\/\/github\.com\/([^/]+)\/([^/]+)\/releases\//;

export function repoFromDl(dl?: string): { owner: string; repo: string } | null {
  if (!dl) return null;
  const match = dl.match(GITHUB_RELEASE_DL);
  if (!match) return null;
  return { owner: match[1], repo: match[2] };
}
